QuickStartProject.Web.UI/Controllers/ContactUsController.cs
using System;
using System.Web.Mvc;
using QuickStartProject.Common;
using QuickStartProject.Emailing;
using QuickStartProject.Emailing.Models;
using QuickStartProject.Web.UI.Models.ContactUs;

namespace QuickStartProject.Web.UI.Controllers
{
    public class ContactUsController : BaseController
    {
        private readonly IMailingService _mailingService;

        public ContactUsController(IMailingService mailingService)
        {
            _mailingService = mailingService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(new ContactUsViewModel());
        }

        [HttpPost]
        public ActionResult Index(ContactUsViewModel model)
        {
            if (!ModelState.IsValid)
            {
                MergeModelState();
                return RedirectToAction("Index");
            }

            ContactUsEmailModel contactUs = ToContactUsEmailModel(model);

            try
            {
                _mailingService.SentContactUsEmail(contactUs);

                ShowInformation("Your message was sent successfully.");
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                Log.Error(
                    "Exception occured while sending contact use email from {0} (email: {1}) user. Subject {2}. Message {3}. Exception {4}",
                    model.SenderName,
                    model.SenderEmail,
                    model.Subject,
                    model.Message,
                    ex);

                ShowError("There was an error while sending your email. Please try again later.");
                return RedirectToAction("Index");
            }
        }

        private ContactUsEmailModel ToContactUsEmailModel(ContactUsViewModel model)
        {
            string contactUsEmail = GetAppSettingsValue("QuickStartProject.ContactUsEmail");
            string subject = string.Format("QuickStartProject Contact Us Email (User: '{0}') - {1}", model.SenderName,
                                           model.Subject);

            ContactUsEmailModel contactUs = ContactUsEmailModel.Create();
            contactUs.SenderName = model.SenderName;
            contactUs.From = model.SenderEmail;
            contactUs.To = contactUsEmail;
            contactUs.Subject = subject;
            contactUs.Message = model.Message;
            return contactUs;
        }
    }
}

QuickStartProject.Web.UI/Views/Shared/_Layout.cshtml
@using QuickStartProject.Web.UI
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
        @Styles.Render("~/Content/bootstrap/css", "~/Content/themes/base/css", "~/Content/css")
        @RenderSection("css", required: false)
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar navbar-static-top">
            <div class="navbar-inner">
                <div class="container">
                    <a href="@Url.Action("Index", "Home")" class="brand">
                        QuickStartProject
                    </a>
                    <ul class="nav">
                        <li class="@(ViewBag.MenuItem == "home" ? "active" : "")">
                            @Html.ActionLink("Home", "Index", "Home")
                        </li>
                        <li class="@(ViewBag.MenuItem == "contact" ? "active" : "")">
                            @Html.ActionLink("Contact Us", "Index", "ContactUs")
                        </li>
                    </ul>

                    <ul class="nav pull-right">
                        @if (Request.IsAuthenticated)
                        {
                            <li>
                                <a href="#" class="pull-right">@ViewBag.Username</a>
                            </li>
                            <li>
                                @Html.ActionLink("Logout", "Logout", "Account", null, new { @class = "pull-right" })
                            </li>
                        }
                        else
                        {
                            <li class="@(ViewBag.MenuItem == "login" ? "active" : "")">
                                @Html.ActionLink("Logon", "Logon", "Account", null, new { @class = "pull-right" })
                            </li>
                            <li class="@(ViewBag.MenuItem == "register" ? "active" : "")">
                                @Html.ActionLink("Register", "Register", "Account", null, new { @class = "pull-right" })
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>        

        <div class="container clearfix">
            <div>
                @if (TempData[Constants.ERROR] != null)
                {
                    <div class="alert alert-error">
                        <button data-dismiss="alert" class="close" type="button">×</button>
                        @TempData[Constants.ERROR].ToString()
                    </div>
                }
                @if (TempData[Constants.INFO] != null)
                {
                    <div class="alert alert-info">
                        <button data-dismiss="alert" class="close" type="button">×</button>
                        @TempData[Constants.INFO].ToString()
                    </div>
                }

                <div class="row">
                    <div class="span12">
                        @RenderBody()
                    </div>
                </div>

            </div>
            <!--end of center content-->
            <div class="row" id="footer">
                <div class="span12">
                    <div id="footer-links-container" class="pull-right">
                        @Html.ActionLink("Home", "Index", "Home") |                        
                        @Html.ActionLink("Contact Us", "Index", "ContactUs")
                    </div>
                </div>
            </div>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
        @Scripts.Render("~/bundles/bootstrap")
    </body>
</html>

QuickStartProject.Web.UI/Views/Shared/_Pager.cshtml
@model Logfox.Domain.Auxilary.IPagedList
@{
    var list = Model;
    const int siteRangeToShow = 2;
    int firstPageToShow = list.PageIndex - siteRangeToShow;
    if (firstPageToShow < 1)
    {
        firstPageToShow = 1;
    }
    int lastPageToShow = list.PageIndex + 2;
    if (lastPageToShow > list.PageCount)
    {
        lastPageToShow = list.PageCount;
    }
}
@if (list.PageCount > 1)
{
    <div class="pagination pagination-centered">
        <ul>
            @if (list.IsPreviousPage)
            {
                <li>@Html.ActionLink("<<", "Index", new { page = 1 })</li>
                <li>@Html.ActionLink("<", "Index", new { page = list.PageIndex - 1 })</li>
            }
            @for (int pageIndex = firstPageToShow; pageIndex <= lastPageToShow; pageIndex++)
            {
                if (pageIndex == list.PageIndex)
                {
                    <li>@Html.ActionLink(pageIndex.ToString(), "Index", new { page = pageIndex }, new { @class = "selected" })</li>
                }
                else
                {
                    <li>@Html.ActionLink(pageIndex.ToString(), "Index", new { page = pageIndex })</li>
                }
            }
            @if (list.IsNextPage)
            {
                <li>@Html.ActionLink(">", "Index", new { page = list.PageIndex + 1 })</li>
                <li>@Html.ActionLink(">>", "Index", new { page = list.PageCount })</li>
            }
        </ul>
    </div>
}